import Mathlib.Algebra.MvPolynomial.Supported

/-!
# Subalgebras omitting one polynomial generator

An algebra equivalence identifies the subalgebra generated by all other variables with the
polynomials of degree zero in the distinguished variable.

These declarations extend Mathlib's algebra APIs.

## Main results

* `MvPolynomial.mem_adjoin_image_X_iff` characterizes the image of the omitted-variable algebra.
-/

noncomputable section

namespace MvPolynomial

variable {R σ A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- The algebra generated by all other generator images has distinguished degree zero. -/
theorem mem_adjoin_image_X_iff (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (f : A) :
    f ∈ Algebra.adjoin R ((fun k : σ => e (X k)) '' {k | k ≠ a}) ↔
      (e.symm f).degreeOf a = 0 := by
  classical
  have hs : (fun k : σ => e (X k)) '' {k | k ≠ a} =
      e.toAlgHom '' (X '' {k | k ≠ a}) := by
    rw [Set.image_image]
    rfl
  have hm : f ∈ (supported R {k | k ≠ a}).map e.toAlgHom ↔
      e.symm f ∈ supported R {k | k ≠ a} := by
    rw [Subalgebra.mem_map]
    constructor
    · rintro ⟨p, hp, hpf⟩
      rw [← hpf]
      change e.symm (e p) ∈ supported R {k | k ≠ a}
      rw [e.symm_apply_apply]
      exact hp
    · intro hf
      exact ⟨e.symm f, hf, e.apply_symm_apply f⟩
  rw [hs, Algebra.adjoin_image, ← supported_eq_adjoin_X, hm, mem_supported]
  constructor
  · intro h
    by_contra ha
    exact h (mem_vars_iff_degreeOf_ne_zero.mpr ha) rfl
  · intro h k hk hka
    subst k
    exact (mem_vars_iff_degreeOf_ne_zero.mp hk) h

end MvPolynomial
