import Schubert.SymmetricFunctions.ForMathlib.GeneratorCoefficients
import Schubert.SymmetricFunctions.ForMathlib.GeneratorSubalgebra

/-! # Coefficients transported through polynomial presentations

These declarations extend Mathlib's algebra-equivalence API.

## Main results

* `AlgEquiv.generatorCoeff_generator_pow` extracts a generator power.
* `AlgEquiv.mem_adjoin_generator_iff` identifies the algebra omitting one generator.
* `AlgEquiv.generatorCoeff_generator_mul` extracts an independent coefficient.
* `AlgEquiv.generatorCoeff_reconstruction` writes an element as the sum of its generator
  coefficients times generator powers.
* `AlgEquiv.generatorCoeff_sum_mul_pow` shows that such an expansion is unique.
-/

noncomputable section

namespace AlgEquiv

variable {R σ A : Type*} [CommRing R] [CommRing A] [Algebra R A]

/-- Extraction on a presentation image is transported polynomial extraction. -/
theorem generatorCoeff_image (e : MvPolynomial σ R ≃ₐ[R] A)
    (a : σ) (j : ℕ) (p : MvPolynomial σ R) :
    e.generatorCoeff a j (e p) = e (MvPolynomial.variableCoeff R a j p) := by
  rw [generatorCoeff_apply, e.symm_apply_apply]

/-- Generator extraction is additive. -/
theorem generatorCoeff_add (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (j : ℕ) (f g : A) :
    e.generatorCoeff a j (f + g) = e.generatorCoeff a j f + e.generatorCoeff a j g :=
  map_add _ _ _

/-- Generator extraction respects scalar multiplication. -/
theorem generatorCoeff_smul (e : MvPolynomial σ R ≃ₐ[R] A)
    (a : σ) (j : ℕ) (r : R) (f : A) :
    e.generatorCoeff a j (r • f) = r • e.generatorCoeff a j f := map_smul _ _ _

/-- Scalar constants have only their coefficient of order zero. -/
theorem generatorCoeff_constant (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (j : ℕ) (r : R) :
    e.generatorCoeff a j (algebraMap R A r) = if j = 0 then algebraMap R A r else 0 := by
  classical
  rw [generatorCoeff_apply, e.symm.commutes, MvPolynomial.algebraMap_eq,
    MvPolynomial.variableCoeff_C]
  simp only [apply_ite, ← MvPolynomial.algebraMap_eq, e.commutes, map_zero]
  split_ifs <;> rfl

/-- A distinguished generator power has exactly its expected coefficient. -/
theorem generatorCoeff_generator_pow (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (j k : ℕ) :
    e.generatorCoeff a j (e (MvPolynomial.X a) ^ k) = if k = j then 1 else 0 := by
  classical
  rw [generatorCoeff_apply, map_pow, e.symm_apply_apply, MvPolynomial.variableCoeff_X_pow]
  simp only [apply_ite, map_one, map_zero]
  split_ifs <;> rfl

/-- Every other generator has only its coefficient of order zero. -/
theorem generatorCoeff_other_generator (e : MvPolynomial σ R ≃ₐ[R] A)
    (a b : σ) (hb : b ≠ a) (j : ℕ) :
    e.generatorCoeff a j (e (MvPolynomial.X b)) =
      if j = 0 then e (MvPolynomial.X b) else 0 := by
  classical
  rw [generatorCoeff_apply, e.symm_apply_apply, MvPolynomial.variableCoeff_X_of_ne R a b hb]
  simp only [apply_ite, map_zero]
  split_ifs <;> rfl

/-- The other generator images generate precisely the elements of generator degree zero. -/
theorem mem_adjoin_generator_iff (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (f : A) :
    f ∈ Algebra.adjoin R ((fun k : σ => e (MvPolynomial.X k)) '' {k | k ≠ a}) ↔
      e.generatorDegree a f = 0 := MvPolynomial.mem_adjoin_image_X_iff e a f

/-- Extracted coefficients belong to the algebra generated by all other generator images. -/
theorem generatorCoeff_mem_adjoin (e : MvPolynomial σ R ≃ₐ[R] A)
    (a : σ) (j : ℕ) (f : A) :
    e.generatorCoeff a j f ∈
      Algebra.adjoin R ((fun k : σ => e (MvPolynomial.X k)) '' {k | k ≠ a}) :=
  (e.mem_adjoin_generator_iff a _).mpr (e.generatorDegree_generatorCoeff a j f)

/-- Multiplying an independent element by a matching generator power recovers that element. -/
theorem generatorCoeff_generator_mul (e : MvPolynomial σ R ≃ₐ[R] A)
    (a : σ) (j : ℕ) (g : A) (hg : e.generatorDegree a g = 0) :
    e.generatorCoeff a j (e (MvPolynomial.X a) ^ j * g) = g := by
  rw [generatorCoeff_mul_of_degree_zero e a j _ g hg, generatorCoeff_generator_pow]
  simp only [ite_true, one_mul]

/-- An element is the finite sum of its generator coefficients times the generator powers. -/
theorem generatorCoeff_reconstruction (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (f : A) :
    f = ∑ j ∈ Finset.range (e.generatorDegree a f + 1),
      e.generatorCoeff a j f * e (MvPolynomial.X a) ^ j := by
  conv_lhs => rw [← e.apply_symm_apply f,
    MvPolynomial.variableCoeff_reconstruction R a (e.symm f)]
  simp only [map_sum, map_mul, map_pow, generatorDegree, generatorCoeff_apply]

/-- The coefficients of a finite expansion in powers of one generator, whose coefficients have
degree zero in that generator, are the generator coefficients of the expanded element. -/
theorem generatorCoeff_sum_mul_pow (e : MvPolynomial σ R ≃ₐ[R] A) (a : σ) (N : ℕ)
    (c : ℕ → A) (hc : ∀ i, e.generatorDegree a (c i) = 0) (j : ℕ) :
    e.generatorCoeff a j (∑ i ∈ Finset.range N, c i * e (MvPolynomial.X a) ^ i) =
      if j < N then c j else 0 := by
  classical
  rw [map_sum]
  have hterm : ∀ i, e.generatorCoeff a j (c i * e (MvPolynomial.X a) ^ i) =
      if i = j then c i else 0 := by
    intro i
    rw [mul_comm, generatorCoeff_mul_of_degree_zero e a j _ _ (hc i),
      generatorCoeff_generator_pow]
    split_ifs <;> simp
  simp only [hterm, Finset.sum_ite_eq', Finset.mem_range]

end AlgEquiv
